name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "30 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_ru
        run: bash ./health-check.sh

permissions:
  contents: write 
  pull-requests: write
  issues: write
